#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys
import os


def only_keep_path(path_to_file):
    index_of_path_end = path_to_file.rfind("/")
    if index_of_path_end == -1:
        return "./"
    return path_to_file[: index_of_path_end + 1]


def is_absoute_path(path_to_file):
    return path_to_file[0] == "/"


def main():
    file_path = sys.argv[1]

    if not is_absoute_path(file_path):
        file_path = os.getcwd() + "/" + file_path

    # create empty file if it doesn't exist
    if not os.path.exists(file_path):
        with open(file_path, "w") as finout:
            finout.write("# Timestamps\n")
    # test if there already a line with timestamps
    with open(file_path, "r+", encoding="UTF-8") as finout:
        if not finout.readline().startswith("# Timestamps"):
            finout.write("# Timestamps\n")

    with open("/tmp/timestamps_path", "w") as finout:
        finout.write(file_path)


if __name__ == "__main__":
    main()
