#!/usr/bin/env python

import sys
import re
import requests
from bs4 import BeautifulSoup
import subprocess

youtube_link = sys.argv[1]


# function that finds out youtube video title by its link
def get_youtube_video_title(youtube_link):
    r = requests.get(youtube_link)
    soup = BeautifulSoup(r.text)

    link = soup.find_all(name="title")[0]
    title = str(link)
    title = title.replace("<title>", "")
    title = title.replace("</title>", "")

    return title


# function that finds out youtube video ID by its link
def get_youtube_video_id(youtube_link):
    # example link: https://youtu.be/CN-zcpScR88?feature=shared
    id = re.search("https://youtu\.be/(.+)?feature=shared", youtube_link).group(1)
    return id


# function that replaces every space in string with underscore
def replace_spaces_with_underscore(string):
    string = string.replace(" ", "_")
    return string


def main():
    id = get_youtube_video_id(youtube_link)
    title = replace_spaces_with_underscore(get_youtube_video_title(youtube_link))
    # execute another python script with arguments in a virutal environment
    subprocess.call(
        [
            "/home/areo/Repositories/lecture_to_markdown_with_speech/virtual_env/bin/python",
            "video_subtitles",
            f"{id}",
            f"{title}",
        ]
    )
    # # move file from one directory to another
    # subprocess.call(
    #     [
    #         "mv",
    #         f"/home/areo/Documents/virtual_env/{title}.subtitles",
    #         f"/home/areo/Documents/Studium/Semester_1_Master/Cyber_Physical_Systems/slides/bonus/{title}.subtitles",
    #     ]
    # )
    subprocess.call(["set_as_timestamps_file", f"{title}.md"])


if __name__ == "__main__":
    main()
